In [1]:
import numpy as np
import pandas as pd
import ast

In [2]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [3]:
 movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
movies = movies.merge(credits,on='title')

In [6]:
movies=movies[["movie_id","title","overview","genres","keywords","cast","crew"]]

In [7]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [9]:
movies.dropna(inplace=True)

In [10]:
movies.duplicated().sum()

0

In [11]:
movies.loc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [12]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [13]:
movies["genres"]=movies["genres"].apply(convert)

In [14]:
movies['keywords']=movies['keywords'].apply(convert)

In [15]:
def convert3(obj):
    L=[]
    counter = 0 
    for i in ast.literal_eval(obj):
        if counter !=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [16]:
movies['cast']=movies['cast'].apply(convert3)

In [17]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i["job"]=="Director":
            L.append(i['name'])
            break
    return L

In [18]:
movies["crew"]=movies["crew"].apply(fetch_director)

In [19]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [20]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [21]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keyword']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])

In [22]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,keyword
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, ScienceFiction]","[Action, Adventure, Fantasy, ScienceFiction]","[Action, Adventure, Fantasy, ScienceFiction]"
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[Adventure, Fantasy, Action]","[Adventure, Fantasy, Action]"
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[Action, Adventure, Crime]","[Action, Adventure, Crime]"
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[Action, Crime, Drama, Thriller]","[Action, Crime, Drama, Thriller]"
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[based on novel, mars, medallion, space travel...","[Action, Adventure, ScienceFiction]","[Action, Adventure, ScienceFiction]","[Action, Adventure, ScienceFiction]"

In [23]:
movies['tags']=movies['overview'] + movies['genres'] + movies['keyword'] + movies['cast'] + movies['crew']

In [24]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,keyword,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, ScienceFiction]","[Action, Adventure, Fantasy, ScienceFiction]","[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[Adventure, Fantasy, Action]","[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[Action, Adventure, Crime]","[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[Action, Crime, Drama, Thriller]","[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[based on novel, mars, medallion, space travel...","[Action, Adventure, ScienceFiction]","[Action, Adventure, ScienceFiction]","[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili..."

In [25]:
new_df = movies[['movie_id','title','tags']]

In [26]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\Amal\AppData\Local\Temp/ipykernel_34052/487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [27]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [28]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\Amal\AppData\Local\Temp/ipykernel_34052/3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [29]:
import nltk

In [30]:
from  nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [31]:
def stem (text):
    y = []
    for i in text .split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [32]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\Amal\AppData\Local\Temp/ipykernel_34052/3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [33]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [35]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [36]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '10th',
 '11',
 '12',
 '12th',
 '13',
 '14',
 '15',
 '150',
 '15th',
 '16',
 '16th',
 '17',
 '17th',
 '18',
 '1863',
 '1890',
 '18th',
 '19',
 '1910',
 '1920',
 '1927',
 '1930',
 '1930s',
 '1937',
 '1940',
 '1940s',
 '1941',
 '1944',
 '1945',
 '1950',
 '1950s',
 '1955',
 '1959',
 '1960',
 '1960s',
 '1962',
 '1964',
 '1965',
 '1967',
 '1969',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1976',
 '1977',
 '1979',
 '1980',
 '1980s',
 '1984',
 '1985',
 '1986',
 '1987',
 '1990',
 '1994',
 '1995',
 '1996',
 '1997',
 '1999',
 '19th',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2007',
 '2008',
 '2009',
 '2011',
 '2012',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '27',
 '30',
 '300',
 '35',
 '3d',
 '40',
 '47',
 '50',
 '500',
 '51',
 '60',
 '60s',
 '70',
 '7th',
 '80',
 'aaron',
 'abandon',
 'abbi',
 'abduct',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abroad',
 'absolut',
 'abus',
 'abuse',
 'academ',
 'academi',
 'academy',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'acquir',
 'act',
 'action',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'ada',
 'adam',
 'adams',
 'adapt',
 'add',
 'addict',
 'addiction',
 'addit',
 'addl',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adolf',
 'adopt',
 'ador',
 'adrift',
 'adult',
 'adulthood',
 'adults',
 'advanc',
 'advantag',
 'advantage',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advice',
 'advis',
 'affair',
 'affect',
 'affection',
 'afflict',
 'affluent',
 'afford',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'aftermath',
 'afternoon',
 'ag',
 'age',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'ail',
 'aim',
 'air',
 'airborn',
 'aircraft',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'alaskan',
 'albert',
 'alcohol',
 'aldou',
 'alec',
 'alex',
 'alexia',
 'alfi',
 'algeria',
 'ali',
 'alic',
 'alice',
 'alien',
 'aliens',
 'alik',
 'alike',
 'aliv',
 'alive',
 'alleg',
 'allegedli',
 'allen',
 'alli',
 'allianc',
 'allies',
 'allow',
 'alon',
 'alongsid',
 'alpha',
 'alreadi',
 'alt',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amateur',
 'amaz',
 'ambassador',
 'ambit',
 'ambiti',
 'ambush',
 'america',
 'american',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amus',
 'amy',
 'ana',
 'anakin',
 'analyst',
 'ancient',
 'anderson',
 'andi',
 'andrew',
 'andy',
 'angel',
 'angela',
 'angeles',
 'anger',
 'angri',
 'ani',
 'anim',
 'animal',
 'animals',
 'ann',
 'anna',
 'anne',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'answers',
 'ant',
 'anthoni',
 'anti',
 'antic',
 'antiqu',
 'anton',
 'antonio',
 'anyon',
 'anyth',
 'apart',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appli',
 'appoint',
 'appreci',
 'apprehend',
 'apprentic',
 'approach',
 'approaches',
 'april',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'army',
 'arnold',
 'arrang',
 'array',
 'arrest',
 'arrested',
 'arriv',
 'arrive',
 'arrives',
 'arrog',
 'art',
 'arthur',
 'articl',
 'artifact',
 'artifici',
 'artist',
 'artists',
 'ash',
 'ashley',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assassins',
 'assault',
 'assembl',
 'assign',
 'assignment',
 'assist',
 'assistant',
 'associ',
 'assort',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'athlet',
 'atlant',
 'atom',
 'attach',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attitud',
 'attorney',
 'attract',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'austrian',
 'author',
 'authorities',
 'authority',
 'auto',
 'autobiograph',
 'avail',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awe',
 'awesom',
 'awkward',
 'awri',
 'awry',
 'axel',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backstag',
 'backup',
 'backwat',
 'backwood',
 'backyard',
 'bad',
 'badli',
 'bag',
 'bahama',
 'bail',
 'baker',
 'balanc',
 'ball',
 'ballet',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'banish',
 'bank',
 'banker',
 'bar',
 'barbara',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrier',
 'barry',
 'bars',
 'bas',
 'base',
 'basebal',
 'baseball',
 'basement',
 'basket',
 'basketbal',
 'basketball',
 'batman',
 'battalion',
 'battl',
 'battle',
 'battlefield',
 'baxter',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beasts',
 'beat',
 'beaten',
 'beau',
 'beauti',
 'beautiful',
 'beauty',
 'becam',
 'becaus',
 'becca',
 'becki',
 'beckon',
 'becom',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'beg',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'beliefs',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'bend',
 'beneath',
 'benefit',
 'benjamin',
 'bennett',
 'bent',
 'berlin',
 'best',
 'bet',
 'beth',
 'betray',
 'betrayal',
 'better',
 'betti',
 'beverli',
 'biblic',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bilbo',
 'billi',
 'billion',
 'billionair',
 'bind',
 'biograph',
 'biographi',
 'biolog',
 'biologist',
 'biopic',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bitter',
 'bizarr',
 'black',
 'blackmail',
 'blade',
 'blake',
 'blame',
 'blart',
 'blaze',
 'blend',
 'bless',
 'blind',
 'bliss',
 'block',
 'blofeld',
 'blonde',
 'blood',
 'bloodi',
 'bloodthirsti',
 'bloom',
 'blossom',
 'blow',
 'blu',
 'blue',
 'blur',
 'board',
 'boat',
 'bob',
 'bobbi',
 'bobby',
 'bodi',
 'body',
 'bodyguard',
 'bohemian',
 'bold',
 'bolt',
 'bomb',
 'bond',
 'bone',
 'boo',
 'book',
 'books',
 'boot',
 'border',
 'bore',
 'boredom',
 'boring',
 'born',
 'borrow',
 'boss',
 'boston',
 'botch',
 'bounc',
 'bound',
 'boundari',
 'bounti',
 'bourn',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyd',
 'boyfriend',
 'boys',
 'brad',
 'brain',
 'brand',
 'brandon',
 'brave',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakup',
 'breath',
 'breed',
 'brent',
 'brew',
 'brian',
 'brick',
 'bride',
 'bridg',
 'bridge',
 'brief',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronson',
 'brook',
 'brooklyn',
 'brother',
 'brotherhood',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'brutal',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'budget',
 'bug',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bump',
 'bunch',
 'bunni',
 'buri',
 'burn',
 'burton',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butch',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'cabl',
 'caesar',
 'cain',
 'cal',
 'cale',
 'caleb',
 'california',
 'calm',
 'calvin',
 'came',
 'camera',
 'cameraman',
 'cameron',
 'camp',
 'campaign',
 'campbel',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candid',
 'canin',
 'capabl',
 'cape',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'captured',
 'car',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'cargo',
 'caribbean',
 'carl',
 'carlo',
 'carmen',
 'carol',
 'carolina',
 'carri',
 'cartel',
 'carter',
 'case',
 'casey',
 'cash',
 'casino',
 'cast',
 'castl',
 'castle',
 'casual',
 'cat',
 'catastroph',
 'catch',
 'catherin',
 'cathol',
 'cattl',
 'caught',
 'caus',
 'cause',
 'cave',
 'cebe',
 'cedric',
 'celebr',
 'celebration',
 'celebrity',
 'cell',
 'censor',
 'cent',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'cesar',
 'chad',
 'chagrin',
 'chain',
 'chair',
 'chairman',
 'challeng',
 'challenge',
 'chamber',
 'champ',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channel',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charlott',
 'charm',
 'chart',
 'chase',
 'chat',
 'chauffeur',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chelsea',
 'chemic',
 'chemistri',
 'cher',
 'cherish',
 'chest',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childhood',
 'children',
 'chili',
 'chill',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chloe',
 'chocol',
 'choic',
 'choice',
 'chon',
 'choos',
 'chopra',
 'chose',
 'chosen',
 'chri',
 'chrissi',
 'christ',
 'christian',
 'christin',
 'christina',
 'christma',
 'christmas',
 'christoph',
 'chronicl',
 'chuck',
 'chucki',
 'church',
 'cia',
 'cindi',
 'cinema',
 'circl',
 'circle',
 'circu',
 'circuit',
 'circumst',
 'circumstances',
 'citi',
 'cities',
 'citizen',
 'citizens',
 'city',
 'civil',
 'civilian',
 'civilization',
 'clad',
 'claim',
 'clair',
 'clan',
 'clark',
 'clash',
 'class',
 'classic',
 'classmat',
 'classmates',
 'claudia',
 'clay',
 'clayton',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'climat',
 'climb',
 'climber',
 'clock',
 'clone',
 'close',
 'closer',
 'closest',
 'cloud',
 'club',
 'clubs',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'coastal',
 'cocain',
 'cocki',
 'code',
 'codi',
 'cohen',
 'col',
 'cold',
 'cole',
 'colin',
 'collaps',
 'collapse',
 'colleagu',
 'colleague',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collide',
 'collin',
 'collis',
 'colon',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'com',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comfort',
 'comic',
 'coming',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'commitment',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compel',
 'compet',
 'competit',
 'competition',
 'complet',
 'complete',
 'complex',
 'complic',
 'compos',
 'compound',
 'compromis',
 'compton',
 'compuls',
 'comput',
 'computer',
 'conan',
 'conceal',
 'concern',
 'concert',
 'conclusion',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confid',
 'confin',
 'confirm',
 'conflict',
 'confront',
 'confus',
 'connect',
 'connecticut',
 'conni',
 'connor',
 'conquer',
 'conquest',
 'conrad',
 'conscience',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contempl',
 'contemporari',
 'contend',
 'content',
 'contest',
 'contin',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 ...]

In [37]:
ps.stem('accident')

'accid'

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

In [39]:
similarity = cosine_similarity(vectors)

In [40]:
def recommend(movie):
    movie_index = new_df[new_df['title']==movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [41]:
recommend("9")

X-Men: The Last Stand
The Matrix Revolutions
Jurassic World
X-Men Origins: Wolverine
A Sound of Thunder